### ISSUE TITLE
Improved error handling for the video region checking

### ISSUE THREAD

**Issue by jodrell2000** [jodrell2000/DaManagement#137]
Robo barfs out errors when...
- a YT video has no content details to check
- the track being played isn't a YT video so has no details to check
- the YT token has expired

Some sensible error reports about which has happened would be nice as the URL to fetch the new token can get swamped in the errors atm

Example log crud...

```
(node:113173) UnhandledPromiseRejectionWarning: Error: invalid_grant
    at Gaxios._request (/home/roboto/Documents/git/DaManagement/node_modules/gaxios/build/src/gaxios.js:129:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.refreshTokenNoCache (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:174:21)
    at async OAuth2Client.getRequestMetadataAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:284:17)
    at async OAuth2Client.requestAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:357:23)
    at async getRegionRestrictions (/home/roboto/Documents/git/DaManagement/modules/videoModule.js:72:39)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:113173) Error: invalid_grant
    at Gaxios._request (/home/roboto/Documents/git/DaManagement/node_modules/gaxios/build/src/gaxios.js:129:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.refreshTokenNoCache (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:174:21)
    at async OAuth2Client.getRequestMetadataAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:284:17)
    at async OAuth2Client.requestAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:357:23)
    at async getRegionRestrictions (/home/roboto/Documents/git/DaManagement/modules/videoModule.js:72:39)
```

```
Error loading JSON from file /home/roboto/.credentials/theManagementCredentials.json : Error: ENOENT: no such file or directory, open '/home/roboto/.credentials/theManagementCredentials.json'
Authorize this app by visiting this url:  https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly&response_type=code&client_id=745466678335-91xxxxxxk3vfmp.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Enter the code from that page here:
Error while trying to retrieve access token GaxiosError: invalid_request
    at Gaxios._request (/home/roboto/Documents/git/DaManagement/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.getTokenAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:124:21) {
  response: {
    config: {
      method: 'POST',
      url: 'https://oauth2.googleapis.com/token',
      data: 'code=&client_id=745466678335-91vqbjpvpjmxxxxx3vfmp.apps.googleusercontent.com&client_secret=zvcq7L-xxxxxx&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&grant_type=authorization_code&code_verifier=',
      headers: [Object],
      paramsSerializer: [Function: paramsSerializer],
      body: 'code=&client_id=745466678335-91vqbjxxxxxx0vk3vfmp.apps.googleusercontent.com&client_secret=zvcq7L-xxxxx&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&grant_type=authorization_code&code_verifier=',
      validateStatus: [Function: validateStatus],
      responseType: 'json'
    },
    data: {
      error: 'invalid_request',
      error_description: 'Missing required parameter: code'
    },
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 17 Jan 2022 10:18:46 GMT',
      expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
      pragma: 'no-cache',
      server: 'scaffolding on HTTPServer2',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request',
    request: { responseURL: 'https://oauth2.googleapis.com/token' }
  },
  config: {
    method: 'POST',
    url: 'https://oauth2.googleapis.com/token',
    data: 'code=&client_id=745466678335-91vqbjpvpjm9a0bb7hbls8m20vk3vfmp.apps.googleusercontent.com&client_secret=zvcq7L-lUcBWvvWtajN1tzJB&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&grant_type=authorization_code&code_verifier=',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'google-api-nodejs-client/7.11.0',
      'x-goog-api-client': 'gl-node/14.17.5 auth/7.11.0',
      Accept: 'application/json'
    },
    paramsSerializer: [Function: paramsSerializer],
    body: 'code=&client_id=745466678335-91vqbjpvpjm9a0bb7hbls8m20vk3vfmp.apps.googleusercontent.com&client_secret=zvcq7L-lUcBWvvWtajN1tzJB&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&grant_type=authorization_code&code_verifier=',
    validateStatus: [Function: validateStatus],
    responseType: 'json'
  },
  code: '400'
}
(node:113173) UnhandledPromiseRejectionWarning: Error: invalid_request
    at Gaxios._request (/home/roboto/Documents/git/DaManagement/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.getTokenAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:124:21)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:113173) Error: invalid_request
    at Gaxios._request (/home/roboto/Documents/git/DaManagement/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.getTokenAsync (/home/roboto/Documents/git/DaManagement/node_modules/google-auth-library/build/src/auth/oauth2client.js:124:21)
```

**Comment by jodrell2000** [comment]
Robo played a track that showed that the account that had uploaded it had closed. The last two lines in the log were,
```
Error occurred in videoFunctions.queryVideoDetails() : TypeError: Cannot read property 'contentDetails' of undefined
Error occurred in videoFunctions.checkVideoRegionAlert() : TypeError: Cannot destructure property 'regionRestriction' of '(intermediate value)' as it is undefined.
```

We should probably
a) date/time stamp the errors
b) see if we can recognise that specific error and have Robo skip, then remove that track from his playlist (guess we need to figure that out first!)
