### ISSUE TITLE
/guilty crashes the bot

### ISSUE THREAD

**Issue by jodrell2000** [jodrell2000/DaManagement#202]
Issuing the command /guilty causes a crash

```
/home/opc/git/DaManagement/modules/chatModule.js:39
                theMessage = theMessage.replace( "@senderUsername", "@" + senderUsername );
                                        ^

TypeError: Cannot read property 'replace' of null
    at Object.buildUserToUserRandomMessage (/home/opc/git/DaManagement/modules/chatModule.js:39:41)
    at Object.textMessageTheDJ (/home/opc/git/DaManagement/modules/chatModule.js:70:42)
    at Object.dynamicChatCommand (/home/opc/git/DaManagement/modules/chatModule.js:95:26)
    at Object.parseCommands (/home/opc/git/DaManagement/modules/commandModule.js:503:31)
    at Bot.<anonymous> (/home/opc/git/DaManagement/DaManagement.js:309:26)
    at Bot.emit (events.js:400:28)
    at Bot.treatCommand (/home/opc/git/DaManagement/node_modules/ttapi/src/bot.js:319:17)
    at Bot.treatPacket (/home/opc/git/DaManagement/node_modules/ttapi/src/bot.js:326:17)
    at Bot.onMessage (/home/opc/git/DaManagement/node_modules/ttapi/src/bot.js:336:17)
    at WebSocket.<anonymous> (/home/opc/git/DaManagement/node_modules/ttapi/src/bot.js:110:21)
Restarting
```

**Comment by jodrell2000** [comment]
Caused by an issue in the chat.json data in that the command had 'null' as a message and no pictures, however the code shouldn't die when this happens
